export {
  decodeResourceLifecycleReport,
  encodeResourceLifecycleReport,
  ResourceLifecycleFailure,
  ResourceLifecycleReportSchema,
  ResourceLifecycleScriptSchema,
  resourceLifecycleBounds,
  traceResourceLifecycle,
  type AcquisitionOutcome,
  type ExitCause,
  type FinalizerOutcome,
  type ResourceCleanupReport,
  type ResourceLifecycleEvent,
  type ResourceLifecycleFinalizerFailure,
  type ResourceLifecycleLawSummary,
  type ResourceLifecycleObservation,
  type ResourceLifecycleReport,
  type ResourceLifecycleResourceReport,
  type ResourceLifecycleScopeReport,
  type ResourceLifecycleScript,
} from "./model.ts";
