#!/usr/bin/env bun
import { BunCrypto } from "@effect/platform-bun";
import { readFile, unlink } from "node:fs/promises";
import { resolve } from "node:path";
import { Console, Data, Effect } from "effect";
import { runCommand, runMain, requireTool } from "../lib/command.ts";
import {
  decodePortableBoundary,
  encodeWitMappingManifest,
  generateWitMapping,
  type PortableBoundaryInput,
} from "../../src/wit-mapping/index.ts";
import { canonicalWitMappingSummaryJson } from "../../src/wit-mapping/canonical.ts";
import { stringifyCanonicalJson } from "../../src/references/canonical-json.ts";

class AcceptanceFailure extends Data.TaggedError("AcceptanceFailure")<{
  readonly message: string;
}> {}

const root = resolve(import.meta.dirname, "../..");
const nodeExecutable = process.env.SEMANTIC_NODE_BIN ?? "node";
const fixturePath = resolve(root, "examples/wit-mapping/inventory.input.json");
const witGoldenPath = resolve(root, "examples/wit-mapping/inventory.wit.golden");
const manifestGoldenPath = resolve(root, "examples/wit-mapping/inventory.manifest.json.golden");
const summaryGoldenPath = resolve(root, "examples/wit-mapping/inventory.summary.json.golden");

const ensure = (condition: boolean, message: string): Effect.Effect<void, AcceptanceFailure> =>
  condition ? Effect.void : Effect.fail(new AcceptanceFailure({ message }));

const readText = (path: string): Effect.Effect<string, AcceptanceFailure> =>
  Effect.tryPromise({
    try: () => readFile(path, "utf8"),
    catch: (cause) => new AcceptanceFailure({ message: `cannot read ${path}: ${String(cause)}` }),
  });

const capture = (
  command: ReadonlyArray<string>,
): Effect.Effect<
  { readonly stdout: string; readonly stderr: string; readonly exitCode: number },
  AcceptanceFailure
> =>
  Effect.try({
    try: () => {
      const result = Bun.spawnSync({
        cmd: [...command],
        cwd: root,
        stdout: "pipe",
        stderr: "pipe",
      });
      return {
        stdout: result.stdout.toString(),
        stderr: result.stderr.toString(),
        exitCode: result.exitCode,
      };
    },
    catch: (cause) =>
      new AcceptanceFailure({ message: `cannot execute ${command.join(" ")}: ${String(cause)}` }),
  });

const decodeFixture = (source: string): Effect.Effect<PortableBoundaryInput, AcceptanceFailure> =>
  Effect.try({
    try: () => JSON.parse(source) as unknown,
    catch: (cause) =>
      new AcceptanceFailure({ message: `cannot parse fixture JSON: ${String(cause)}` }),
  }).pipe(
    Effect.flatMap((input) => {
      const decoded = decodePortableBoundary(input);
      return decoded.status === "rejected"
        ? Effect.fail(new AcceptanceFailure({ message: JSON.stringify(decoded.diagnostics) }))
        : Effect.succeed(decoded.value);
    }),
  );

const program = Effect.gen(function* () {
  const source = yield* readText(fixturePath);
  const decoded = yield* decodeFixture(source);
  const artifact = yield* generateWitMapping(decoded);
  const witGolden = yield* readText(witGoldenPath);
  const manifestGolden = yield* readText(manifestGoldenPath);
  const summaryGolden = yield* readText(summaryGoldenPath);
  const manifestBytes = encodeWitMappingManifest(artifact.manifest);
  const summary = canonicalWitMappingSummaryJson({
    format: artifact.manifest.format,
    wit: artifact.wit,
    manifest: artifact.manifest,
    wit_identity: artifact.wit_identity,
    manifest_identity: artifact.manifest_identity,
    wit_bytes: new TextEncoder().encode(artifact.wit).byteLength,
    manifest_bytes: manifestBytes.byteLength,
  });
  yield* ensure(artifact.wit === witGolden, "WIT golden differs from generated bytes");
  yield* ensure(
    new TextDecoder().decode(manifestBytes) === manifestGolden,
    "manifest golden differs from generated bytes",
  );
  yield* ensure(`${summary}\n` === summaryGolden, "summary golden differs from generated bytes");
  yield* ensure(
    artifact.wit.includes("reserve: async func"),
    "missing native async freestanding function",
  );
  yield* ensure(
    artifact.wit.includes("release: async func"),
    "missing native async resource method",
  );
  yield* ensure(artifact.wit.includes("stream<inventory-event>"), "missing native stream type");
  yield* ensure(
    artifact.wit.includes("future<result<_, inventory-error>>"),
    "missing native future type",
  );
  yield* ensure(
    artifact.wit.includes("import fresh-identifiers;") &&
      artifact.wit.includes("export inventory;"),
    "world direction is not preserved",
  );
  yield* ensure(artifact.wit.includes("borrow<reservation>"), "borrowed resource use is missing");
  yield* ensure(
    artifact.wit.includes("-> result<reservation, inventory-error>"),
    "owned resource result is missing",
  );
  const dimensionKeys = new Set(
    artifact.manifest.semantic_dimensions.map((row) => `${row.kind}:${row.id}`),
  );
  for (const key of [
    "law:rejection-is-noop",
    "law:replay-agrees-with-transition",
    "effect_label:effect.fresh",
    "effect_label:effect.clock",
    "usage_grade:linear",
    "assumption:inventory.initial-state",
    "assumption:inventory/reservation.drop",
    "evidence_requirement:inventory.conformance",
  ])
    yield* ensure(dimensionKeys.has(key), `manifest omitted semantic dimension ${key}`);
  yield* ensure(
    artifact.manifest.unsupported_claims.length === 5,
    "manifest does not retain all unsupported claim classes",
  );
  const unsupportedInput = structuredClone(JSON.parse(source)) as Record<string, unknown>;
  const unsupportedInterfaces = unsupportedInput.interfaces as Array<Record<string, unknown>>;
  const unsupportedInventory = unsupportedInterfaces[1]!;
  const unsupportedFunctions = unsupportedInventory.functions as Array<Record<string, unknown>>;
  const unsupportedParams = unsupportedFunctions[0]!.params as Array<Record<string, unknown>>;
  unsupportedParams[0]!.type = { kind: "function", params: [], result: "string" };
  const unsupportedDecoded = decodePortableBoundary(unsupportedInput);
  yield* ensure(
    unsupportedDecoded.status === "rejected",
    "unsupported higher-order type was accepted",
  );
  if (unsupportedDecoded.status === "rejected")
    yield* ensure(
      unsupportedDecoded.diagnostics[0]?.code === "type.unsupported",
      "unsupported type did not return a typed diagnostic",
    );
  const ambiguousInput = structuredClone(JSON.parse(source)) as Record<string, unknown>;
  (ambiguousInput.world as Record<string, unknown>).exports = ["fresh-identifiers", "inventory"];
  const ambiguousDecoded = decodePortableBoundary(ambiguousInput);
  yield* ensure(ambiguousDecoded.status === "rejected", "ambiguous world direction was accepted");
  if (ambiguousDecoded.status === "rejected")
    yield* ensure(
      ambiguousDecoded.diagnostics[0]?.code === "world.ambiguous-direction",
      "ambiguous direction did not return a typed diagnostic",
    );

  const changedInput = structuredClone(JSON.parse(source)) as Record<string, unknown>;
  const changedTheory = changedInput.theory as Record<string, unknown>;
  (changedTheory.laws as unknown[]).pop();
  const changedDecoded = decodePortableBoundary(changedInput);
  yield* ensure(changedDecoded.status === "decoded", "law-only descriptor change was rejected");
  if (changedDecoded.status === "decoded") {
    const changed = yield* generateWitMapping(changedDecoded.value);
    yield* ensure(
      changed.wit === artifact.wit && changed.wit_identity === artifact.wit_identity,
      "law-only change altered WIT identity",
    );
    yield* ensure(
      changed.manifest_identity !== artifact.manifest_identity,
      "law-only change did not alter manifest identity",
    );
  }

  const wasmTools = yield* requireTool("accept/0054 wasm-tools", "wasm-tools");
  const version = yield* capture([wasmTools, "--version"]);
  yield* ensure(
    version.exitCode === 0 && version.stdout.includes("wasm-tools 1.254.0"),
    `expected pinned wasm-tools 1.254.0, observed ${version.stdout.trim()}`,
  );
  const positive = yield* capture([wasmTools, "component", "wit", witGoldenPath]);
  yield* ensure(
    positive.exitCode === 0,
    `wasm-tools rejected the generated WIT: ${positive.stderr.trim()}`,
  );
  const native_async = positive.stdout.includes("async func");
  const native_stream = positive.stdout.includes("stream<");
  const native_future = positive.stdout.includes("future<");
  yield* ensure(native_async, "wasm-tools output omitted async func");
  yield* ensure(native_stream, "wasm-tools output omitted stream type");
  yield* ensure(native_future, "wasm-tools output omitted future type");
  const invalidPath = "/tmp/semantic-wit-mapping-invalid.wit";
  yield* Effect.tryPromise({
    try: () => Bun.write(invalidPath, "package semantic:invalid@1.0.0; interface {\n"),
    catch: (cause) =>
      new AcceptanceFailure({ message: `cannot write invalid WIT oracle: ${String(cause)}` }),
  });
  const invalid = yield* capture([wasmTools, "component", "wit", invalidPath]);
  yield* ensure(invalid.exitCode !== 0, "wasm-tools accepted the invalid WIT oracle");
  yield* Effect.tryPromise({
    try: () => unlink(invalidPath),
    catch: (cause) =>
      new AcceptanceFailure({ message: `cannot remove invalid WIT oracle: ${String(cause)}` }),
  });

  const bunSummary = yield* capture(["bun", "src/wit-mapping/main-bun.ts"]);
  const nodeSummary = yield* capture([nodeExecutable, "src/wit-mapping/main-node.ts"]);
  yield* ensure(
    bunSummary.exitCode === 0 && nodeSummary.exitCode === 0,
    "Bun or genuine Node mapper entrypoint failed",
  );
  yield* ensure(
    bunSummary.stdout === nodeSummary.stdout,
    "Bun and genuine Node summary bytes differ",
  );
  yield* ensure(
    `${bunSummary.stdout}` === summaryGolden,
    "entrypoint summary does not match golden bytes",
  );

  for (const command of [
    ["bun", "test", "tests/wit-mapping.test.ts"],
    ["bun", "test", "tests/kernel-finite-sums.test.ts"],
    ["bun", "run", "typecheck"],
    ["bun", "run", "lint"],
    ["bun", "run", "format:check"],
    ["bun", "run", "semproj", "--", "validate"],
    ["bun", "run", "semproj", "--", "generate", "--check"],
  ] as const)
    yield* runCommand(command, { cwd: root });
  yield* Console.log(
    stringifyCanonicalJson({
      wasm_tools_version: version.stdout.trim(),
      parser: {
        positive_exit: positive.exitCode,
        invalid_exit: invalid.exitCode,
        native_async,
        native_stream,
        native_future,
      },
      wit_bytes: new TextEncoder().encode(artifact.wit).byteLength,
      manifest_bytes: manifestBytes.byteLength,
    }),
  );
});

runMain("accept/0054", program.pipe(Effect.provide(BunCrypto.layer)));
